[package]
name = "rusty"
version = "0.1.1"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]
build = "build.rs"

[lib]
doc = true
name = "rush"
path = "src/lib.rs"

[dependencies]
toml = "*"
term = "*"
libc = "*"

[dependencies.clippy]
git = "https://github.com/manishearth/rust-clippy"

[build-dependencies]
gcc = "*"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[profile.doc]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
