#This is a basic config for rusty. The only things that are required are
#[prompt]
#left = ""
#[alias]
#[env_var]


#You can put as many or as few things as you want in alias and env_var. Just the table field is required.

[prompt]
#Translation of below mark up
#User@hostname cwd Root/Not Root
left = "%U@%H %L %R"

[alias]
gc = "git commit"
gpm = "git push master"

[env_var]
EDITOR = "nano"
